# Generated by Django 3.0.7 on 2020-11-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField(blank=True, default=0, null=True)),
                ('vote', models.IntegerField(blank=True, default=0, null=True)),
                ('video', models.BooleanField(blank=True, default=False, null=True)),
                ('poster', models.URLField(blank=True, max_length=1024, null=True)),
                ('adult', models.BooleanField(blank=True, default=False, null=True)),
                ('backdrop', models.URLField(blank=True, max_length=1024, null=True)),
                ('Language', models.CharField(blank=True, max_length=5, null=True)),
                ('original_title', models.CharField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('vote_average', models.IntegerField(blank=True, default=0, null=True)),
                ('overview', models.TextField(blank=True, max_length=554, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('genre_ids', models.ManyToManyField(to='catalog.Genders')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
