# Generated by Django 3.0.7 on 2020-11-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, max_length=4, null=True)),
                ('minimum_age', models.IntegerField(blank=True, default=0, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'classification',
            },
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Language',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='adult',
        ),
        migrations.AddField(
            model_name='movies',
            name='classification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.classification'),
        ),
    ]
