# Generated by Django 3.0.7 on 2020-11-24 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201124_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.classification'),
        ),
    ]
