# Generated by Django 3.0.7 on 2020-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201124_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='indicator',
            field=models.CharField(max_length=4),
        ),
    ]
