# Generated by Django 3.0.7 on 2020-11-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201124_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.classification'),
        ),
    ]
