# Generated by Django 3.0.7 on 2020-11-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201124_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='classification',
            new_name='sorting',
        ),
    ]
