# Generated by Django 3.0.7 on 2020-11-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201124_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='minimum_age',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='sorting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Classification'),
        ),
    ]
